/**
 * Pure YAML emitter for the first-run setup wizard (SetupWizard.tsx).
 * Kept out of the component so a regression script can round-trip it.
 */

/** The wizard fields the YAML depends on. */
export interface SetupYamlInput {
  backendKind: 'filesystem' | 's3';
  fsPath: string;
  s3Endpoint: string;
  s3Region: string;
  s3ForcePathStyle: boolean;
  s3AccessKey: string;
  s3SecretKey: string;
  adminAccessKeyId: string;
  adminSecretKey: string;
  publicBucketName: string;
  enablePublicBucket: boolean;
}

/**
 * Emit a string as a YAML double-quoted scalar that survives both the
 * server's `${env:NAME}` pre-pass and the YAML parser byte-for-byte.
 *
 * - JSON.stringify: a JSON string is a valid YAML double-quoted scalar, so
 *   `"`, `\`, newlines, tabs and a Windows path round-trip exactly.
 * - `$` → `$$`: /config/apply expands `${env:X}` over the raw text before
 *   parsing, and `$$` is its literal-`$` escape (src/config/expansion.rs).
 */
function yamlScalar(v: string): string {
  return JSON.stringify(v.replace(/\$/g, '$$$$'));
}

/** Build the YAML document from the wizard state. Emits the
 *  canonical four-section shape. Fields at their default are
 *  omitted so the produced file is small and diff-friendly. */
export function generateSetupYaml(s: SetupYamlInput): string {
  const lines: string[] = [];
  lines.push('# Generated by the DeltaGlider Proxy setup wizard.');
  lines.push('# Re-run the wizard any time from /_/admin/setup or edit fields below by hand.');
  lines.push('');

  // ── access ─────────────────────────────────────────────
  if (s.adminAccessKeyId || s.adminSecretKey) {
    lines.push('access:');
    if (s.adminAccessKeyId) {
      lines.push(`  access_key_id: ${yamlScalar(s.adminAccessKeyId)}`);
    }
    if (s.adminSecretKey) {
      lines.push(`  secret_access_key: ${yamlScalar(s.adminSecretKey)}`);
    }
    lines.push('');
  }

  // ── storage ────────────────────────────────────────────
  lines.push('storage:');
  if (s.backendKind === 'filesystem') {
    // Use the shorthand form when region/creds aren't needed.
    lines.push(`  filesystem: ${yamlScalar(s.fsPath)}`);
  } else {
    // S3 — use the shorthand form when feasible, full form otherwise.
    lines.push(`  s3: ${yamlScalar(s.s3Endpoint)}`);
    if (s.s3Region && s.s3Region !== 'us-east-1') {
      lines.push(`  region: ${yamlScalar(s.s3Region)}`);
    }
    if (s.s3AccessKey) {
      lines.push(`  access_key_id: ${yamlScalar(s.s3AccessKey)}`);
    }
    if (s.s3SecretKey) {
      lines.push(`  secret_access_key: ${yamlScalar(s.s3SecretKey)}`);
    }
    if (!s.s3ForcePathStyle) {
      lines.push(`  force_path_style: false`);
    }
  }
  if (s.enablePublicBucket && s.publicBucketName.trim()) {
    lines.push('  buckets:');
    lines.push(`    ${yamlScalar(s.publicBucketName.trim())}:`);
    lines.push('      public: true');
  }
  lines.push('');

  return lines.join('\n');
}
