/**
 * Pure YAML emitter for the first-run setup wizard (SetupWizard.tsx).
 * Kept out of the component so a regression script can round-trip it.
 */

import type { EnvOverride } from './envOverrides';

/** The wizard fields the YAML depends on. */
export interface SetupYamlInput {
  backendKind: 'filesystem' | 's3';
  fsPath: string;
  s3Endpoint: string;
  s3Region: string;
  s3ForcePathStyle: boolean;
  s3AccessKey: string;
  s3SecretKey: string;
  adminAccessKeyId: string;
  adminSecretKey: string;
  publicBucketName: string;
  enablePublicBucket: boolean;
}

/**
 * Emit a string as a YAML double-quoted scalar that survives both the
 * server's `${env:NAME}` pre-pass and the YAML parser byte-for-byte.
 *
 * - JSON.stringify: a JSON string is a valid YAML double-quoted scalar, so
 *   `"`, `\`, newlines, tabs and a Windows path round-trip exactly.
 * - `$` → `$$`: /config/apply expands `${env:X}` over the raw text before
 *   parsing, and `$$` is its literal-`$` escape (src/config/expansion.rs).
 */
function yamlScalar(v: string): string {
  return JSON.stringify(v.replace(/\$/g, '$$$$'));
}

/**
 * Which wizard answers an environment variable already gives. Such a field
 * is shown read-only, counts as answered, and is left out of the generated
 * YAML (the file must not fight the environment).
 */
export interface SetupEnvControl {
  adminAccessKeyId: boolean;
  adminSecretKey: boolean;
  /** The environment sets the whole singleton backend (`storage.backend`). */
  backendKind: 'filesystem' | 's3' | null;
}

const NO_ENV_CONTROL: SetupEnvControl = {
  adminAccessKeyId: false,
  adminSecretKey: false,
  backendKind: null,
};

export function setupEnvControl(overrides: readonly EnvOverride[] | undefined): SetupEnvControl {
  const at = (path: string) => overrides?.find((o) => o.yaml_path === path);
  const kind = at('storage.backend.type')?.value;
  return {
    adminAccessKeyId: at('access.access_key_id') !== undefined,
    adminSecretKey: at('access.secret_access_key') !== undefined,
    backendKind: kind === 's3' || kind === 'filesystem' ? kind : null,
  };
}

/** The answers the "Next" button needs on each step. */
export interface SetupStepInput {
  backendKind: 'filesystem' | 's3';
  fsPath: string;
  adminAccessKeyId: string;
  adminSecretKey: string;
  adminSecretKeyConfirm: string;
}

/**
 * Whether the operator may leave `step`. An env-controlled answer counts as
 * given. `isAbsolute` is injected (utils.ts) to keep this module import-free.
 */
export function setupStepComplete(
  step: number,
  s: SetupStepInput,
  env: SetupEnvControl,
  s3TestPassed: boolean,
  isAbsolute: (path: string) => boolean,
): boolean {
  switch (step) {
    case 1:
      if (env.backendKind !== null) return true;
      return s.backendKind === 'filesystem' ? isAbsolute(s.fsPath) : s3TestPassed;
    case 2:
      return (
        (env.adminAccessKeyId || s.adminAccessKeyId.trim().length >= 4) &&
        (env.adminSecretKey ||
          (s.adminSecretKey.length >= 12 && s.adminSecretKey === s.adminSecretKeyConfirm))
      );
    default:
      return step >= 0 && step <= 4;
  }
}

/** Build the YAML document from the wizard state. Emits the
 *  canonical four-section shape. Fields at their default are
 *  omitted so the produced file is small and diff-friendly.
 *  Answers the environment gives (`env`) are left out. */
export function generateSetupYaml(s: SetupYamlInput, env: SetupEnvControl = NO_ENV_CONTROL): string {
  const lines: string[] = [];
  lines.push('# Generated by the DeltaGlider Proxy setup wizard.');
  lines.push('# Re-run the wizard any time from /_/admin/setup or edit fields below by hand.');
  lines.push('');

  // ── access ─────────────────────────────────────────────
  const keyId = env.adminAccessKeyId ? '' : s.adminAccessKeyId;
  const secret = env.adminSecretKey ? '' : s.adminSecretKey;
  if (keyId || secret) {
    lines.push('access:');
    if (keyId) {
      lines.push(`  access_key_id: ${yamlScalar(keyId)}`);
    }
    if (secret) {
      lines.push(`  secret_access_key: ${yamlScalar(secret)}`);
    }
    lines.push('');
  }

  // ── storage ────────────────────────────────────────────
  const publicBucket = s.enablePublicBucket && s.publicBucketName.trim();
  if (env.backendKind !== null && !publicBucket) {
    // Every answer comes from the environment. An empty mapping keeps the
    // document parseable (a comments-only document is not a mapping).
    if (!keyId && !secret) lines.push('{}');
    return lines.join('\n');
  }
  lines.push('storage:');
  if (env.backendKind !== null) {
    // The environment sets the backend; the file leaves it out.
  } else if (s.backendKind === 'filesystem') {
    // Use the shorthand form when region/creds aren't needed.
    lines.push(`  filesystem: ${yamlScalar(s.fsPath)}`);
  } else {
    // S3 — use the shorthand form when feasible, full form otherwise.
    lines.push(`  s3: ${yamlScalar(s.s3Endpoint)}`);
    if (s.s3Region && s.s3Region !== 'us-east-1') {
      lines.push(`  region: ${yamlScalar(s.s3Region)}`);
    }
    if (s.s3AccessKey) {
      lines.push(`  access_key_id: ${yamlScalar(s.s3AccessKey)}`);
    }
    if (s.s3SecretKey) {
      lines.push(`  secret_access_key: ${yamlScalar(s.s3SecretKey)}`);
    }
    if (!s.s3ForcePathStyle) {
      lines.push(`  force_path_style: false`);
    }
  }
  if (publicBucket) {
    lines.push('  buckets:');
    lines.push(`    ${yamlScalar(s.publicBucketName.trim())}:`);
    lines.push('      public: true');
  }
  lines.push('');

  return lines.join('\n');
}
