// SPDX-License-Identifier: BUSL-1.1

//! Content-defined chunking (FastCDC) + 256-bit SimHash similarity sketch.
//!
//! Produces a 32-byte fingerprint of a file's *content* that is:
//! - **Intrinsic**: computed solely from the object's own bytes. Does not
//!   depend on which reference was (or will be) chosen for delta encoding.
//! - **Position-robust**: a 1-byte insertion near the start only shifts
//!   chunks locally; downstream chunks have byte-identical boundaries
//!   because FastCDC cut points are content-defined, not offset-defined.
//! - **Cheap to compare**: Hamming distance (XOR + popcount) on two 256-bit
//!   sketches is O(1), regardless of file size.
//! - **Compact**: 32 bytes per object — fits in S3 user metadata or an
//!   xattr alongside the existing DG fields.
//!
//! ## Why SimHash over FastCDC (not fixed-window shingles)
//!
//! Fixed-size sliding-window shingles are position-sensitive: a 1-byte
//! insertion at the start shifts every subsequent window, making
//! near-duplicate files appear unrelated. FastCDC cuts at content-defined
//! boundaries (gear-table rolling hash), so an insertion only shifts
//! chunks near the insertion point. SimHash folds all chunk hashes into a
//! single 256-bit value where Hamming distance ≈ dissimilarity.
//!
//! ## Storage
//!
//! The sketch is stored as a hex string (64 chars) in `FileMetadata.sketch`
//! and persisted as part of the DG metadata JSON (xattr / S3 user metadata).
//! It is backward-compatible: existing objects without the field deserialize
//! with `None` and are simply absent from the similarity index.

use std::path::Path;

/// The sketch size in bits.
pub const SIMHASH_BITS: usize = 256;

/// The sketch size in bytes (= SIMHASH_BITS / 8).
pub const SIMHASH_BYTES: usize = SIMHASH_BITS / 8; // 32

/// Default Hamming distance threshold below which two objects are considered
/// "similar enough" for xdelta3 to produce a good delta. Tunable at the
/// call site; this is the documented starting point.
pub const SIMILARITY_THRESHOLD_BITS: u32 = 24;

// ── FastCDC parameters ─────────────────────────────────────────────────

const CDC_MIN: usize = 2 * 1024; // 2 KiB — minimum chunk size
const CDC_AVG: usize = 8 * 1024; // 8 KiB — target average chunk size
const CDC_MAX: usize = 64 * 1024; // 64 KiB — maximum chunk size

/// Mask for the average-size cut point. The gear-table rolling hash is
/// ANDed with this mask; when the result equals zero, we cut. This yields
/// an average chunk size of ~`CDC_AVG` bytes (probability 1/MASK).
const CDC_MASK: u64 = (CDC_AVG - 1) as u64; // 0x1FFF for 8 KiB

/// Gear table: 256 pseudorandom u64 values. Fixed seed — deterministic
/// across builds and instances. Generated by SplitMix64 with seed 0x0123456789ABCDEF.
/// Two instances of DGP (or any other tool using this table) produce identical
/// chunk boundaries for identical content, enabling cross-instance sketch
/// compatibility.
const GEAR: [u64; 256] = GEAR_TABLE;

/// Compute the 256-bit SimHash sketch of `data`.
///
/// This is the one-shot entry point for the buffered PUT path (the whole
/// object is in RAM). Returns a 32-byte array.
pub fn sketch_bytes(data: &[u8]) -> [u8; SIMHASH_BYTES] {
    let mut builder = SketchBuilder::new();
    builder.update(data);
    builder.finalize()
}

/// Compute the sketch as a hex string (64 chars), the storage format used
/// in `FileMetadata.sketch`.
pub fn sketch_hex(data: &[u8]) -> String {
    hex::encode(sketch_bytes(data))
}

/// Streaming sketch builder — accumulate chunks from multiple reads, then
/// finalize. Used by the spooled PUT path where the body is streamed from
/// a file, not held in RAM.
pub struct SketchBuilder {
    // SimHash accumulator: for each of the 256 bits, count +1/-1 per chunk.
    acc: [i64; SIMHASH_BITS],
    // FastCDC state
    fp: u64,        // rolling fingerprint
    pos: usize,     // bytes since last chunk start
    buf: Vec<u8>,   // unchunked bytes carried over between updates
    scanned: usize, // bytes in `buf` already fed into fp/pos (resume offset)
}

impl SketchBuilder {
    pub fn new() -> Self {
        Self {
            acc: [0; SIMHASH_BITS],
            fp: 0,
            pos: 0,
            buf: Vec::with_capacity(CDC_MAX * 2),
            scanned: 0,
        }
    }

    /// Feed a chunk of data into the sketch. Can be called multiple times
    /// for streaming ingestion; chunk boundaries are continuous across
    /// calls (the FastCDC state carries over).
    pub fn update(&mut self, data: &[u8]) {
        self.buf.extend_from_slice(data);
        self.drain_chunks(false);
    }

    /// Finalize: process any remaining buffered bytes (flush the last chunk),
    /// then compute the SimHash sign bits.
    pub fn finalize(mut self) -> [u8; SIMHASH_BYTES] {
        self.drain_chunks(true);
        simhash_sign(&self.acc)
    }

    /// Drain complete chunks from `buf`; when `flush` is true, emit the
    /// final (possibly sub-minimum) chunk as well. The `scanned` field
    /// tracks how many bytes of the current in-progress chunk have already
    /// been fed into the rolling hash, so we don't re-hash them on the
    /// next `update` call.
    fn drain_chunks(&mut self, flush: bool) {
        loop {
            let start = self.scanned;
            if start >= self.buf.len() {
                break;
            }
            let remaining = self.buf.len() - start;
            let bytes_to_scan = remaining.min(CDC_MAX.saturating_sub(self.pos));

            let mut cut = None;
            for j in 0..bytes_to_scan {
                let b = self.buf[start + j] as usize;
                self.fp = (self.fp << 1) ^ GEAR[b];
                self.pos += 1;

                if self.pos >= CDC_MIN && (self.fp & CDC_MASK) == 0 {
                    cut = Some(start + j + 1);
                    break;
                }
            }

            match cut {
                Some(total_len) => {
                    // Emit chunk buf[0..total_len].
                    let h = chunk_hash(&self.buf[..total_len]);
                    vote(&mut self.acc, h);
                    self.buf.drain(0..total_len);
                    self.scanned = 0;
                    self.fp = 0;
                    self.pos = 0;
                }
                None => {
                    if self.pos >= CDC_MAX {
                        // Hard cut at CDC_MAX — emit everything scanned so far.
                        let total = start + bytes_to_scan;
                        let h = chunk_hash(&self.buf[..total]);
                        vote(&mut self.acc, h);
                        self.buf.drain(0..total);
                        self.scanned = 0;
                        self.fp = 0;
                        self.pos = 0;
                    } else {
                        // Not enough data to decide yet. Remember how far
                        // we've scanned so the next update resumes here.
                        self.scanned = start + bytes_to_scan;
                        break;
                    }
                }
            }
        }

        if flush && !self.buf.is_empty() {
            let h = chunk_hash(&self.buf);
            vote(&mut self.acc, h);
            self.buf.clear();
            self.scanned = 0;
            self.fp = 0;
            self.pos = 0;
        }
    }
}

impl Default for SketchBuilder {
    fn default() -> Self {
        Self::new()
    }
}

/// Hash a chunk using FNV-1a (fast, good distribution, no deps).
/// We use the 64-bit variant; the high bits feed the SimHash vote.
#[inline]
fn chunk_hash(chunk: &[u8]) -> u64 {
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    let mut h = FNV_OFFSET;
    for &b in chunk {
        h = h.wrapping_mul(FNV_PRIME);
        h ^= b as u64;
    }
    h
}

/// Cast a chunk's hash as a weighted vote into the accumulator.
/// For each of the 256 SimHash bit positions, if the corresponding bit of
/// the chunk hash is 1, increment the accumulator; otherwise decrement.
/// The chunk hash is 64 bits, so we cycle through it 4 times to cover all
/// 256 positions.
#[inline]
fn vote(acc: &mut [i64; SIMHASH_BITS], hash: u64) {
    for (i, val) in acc.iter_mut().enumerate() {
        let bit = (hash >> (i % 64)) & 1;
        if bit == 1 {
            *val += 1;
        } else {
            *val -= 1;
        }
    }
}

/// Convert the signed accumulator into the final 256-bit SimHash:
/// each output bit is 1 if the corresponding accumulator value is > 0.
#[inline]
fn simhash_sign(acc: &[i64; SIMHASH_BITS]) -> [u8; SIMHASH_BYTES] {
    let mut out = [0u8; SIMHASH_BYTES];
    for (i, &val) in acc.iter().enumerate() {
        if val > 0 {
            out[i / 8] |= 1 << (i % 8);
        }
    }
    out
}

/// Hamming distance between two 32-byte sketches (number of differing bits).
/// `a` and `b` must be 32 bytes; returns 0 for identical sketches.
pub fn hamming_distance(a: &[u8], b: &[u8]) -> u32 {
    debug_assert_eq!(a.len(), SIMHASH_BYTES);
    debug_assert_eq!(b.len(), SIMHASH_BYTES);
    let mut dist: u32 = 0;
    for i in 0..SIMHASH_BYTES {
        dist += (a[i] ^ b[i]).count_ones();
    }
    dist
}

/// Hamming distance between two hex-encoded sketches. Returns `None` if
/// either string is not a valid 64-char hex sketch.
pub fn hamming_distance_hex(a: &str, b: &str) -> Option<u32> {
    let a = hex::decode(a).ok()?;
    let b = hex::decode(b).ok()?;
    if a.len() != SIMHASH_BYTES || b.len() != SIMHASH_BYTES {
        return None;
    }
    Some(hamming_distance(&a, &b))
}

/// True iff the two hex-encoded sketches are within `threshold` bits of
/// each other (i.e., the objects are likely similar enough for xdelta3).
pub fn is_similar_hex(a: &str, b: &str, threshold: u32) -> bool {
    match hamming_distance_hex(a, b) {
        Some(d) => d <= threshold,
        None => false,
    }
}

/// Compute the sketch of a file by streaming it (used by the spooled PUT
/// path). Reads the file in 256 KiB blocks, feeds them to a `SketchBuilder`,
/// and returns the hex-encoded sketch.
pub fn sketch_file_hex(path: &Path) -> std::io::Result<String> {
    use std::io::Read;
    let mut f = std::fs::File::open(path)?;
    let mut builder = SketchBuilder::new();
    let mut buf = vec![0u8; 256 * 1024];
    loop {
        let n = f.read(&mut buf)?;
        if n == 0 {
            break;
        }
        builder.update(&buf[..n]);
    }
    Ok(hex::encode(builder.finalize()))
}

// ── Gear table ─────────────────────────────────────────────────────────

/// Generate the 256-entry gear table using SplitMix64 with a fixed seed.
/// This is a `const fn` so the table is compiled in — zero runtime cost
/// on startup, deterministic across builds.
const fn gear_table() -> [u64; 256] {
    let mut table = [0u64; 256];
    let mut state: u64 = 0x0123_4567_89AB_CDEF;

    let mut i = 0;
    while i < 256 {
        // SplitMix64
        state = state.wrapping_add(0x9E3779B97F4A7C15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
        z ^= z >> 31;
        table[i] = z;
        i += 1;
    }
    table
}

const GEAR_TABLE: [u64; 256] = gear_table();

// ── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// Two identical files must produce identical sketches.
    #[test]
    fn test_identical_files_identical_sketch() {
        let data = vec![0x42u8; 100_000];
        let s1 = sketch_hex(&data);
        let s2 = sketch_hex(&data);
        assert_eq!(s1, s2);
        assert_eq!(hamming_distance_hex(&s1, &s2), Some(0));
    }

    /// A small change must produce a small Hamming distance.
    #[test]
    fn test_small_change_small_hamming() {
        let data_a = vec![0x42u8; 200_000];
        let mut data_b = data_a.clone();
        // Change 1 byte near the middle.
        data_b[100_000] = 0x99;

        let sa = sketch_hex(&data_a);
        let sb = sketch_hex(&data_b);
        let dist = hamming_distance_hex(&sa, &sb).expect("valid sketches");
        // A single byte change in uniform data only affects the chunk
        // containing the change (all chunks are identical → only one
        // chunk hash differs). The distance should be very small.
        assert!(
            dist < 40,
            "single-byte change produced Hamming distance {dist}, expected < 40"
        );
    }

    /// Completely unrelated files must produce a large Hamming distance.
    #[test]
    fn test_unrelated_files_large_hamming() {
        // Use genuinely different structured data, not constant-fill.
        // Constant-fill (all 0xAA) produces only one unique chunk hash,
        // so the sketch is determined by a single FNV-1a value — the
        // distance between two such sketches is unpredictable.
        // Structured data with different multipliers produces many
        // different chunk hashes → the SimHash distance reflects true
        // dissimilarity.
        let data_a: Vec<u8> = (0..200_000u32)
            .map(|i| ((i * 31 + 17) % 251) as u8)
            .collect();
        let data_b: Vec<u8> = (0..200_000u32)
            .map(|i| ((i * 97 + 43) % 251) as u8)
            .collect();
        let sa = sketch_hex(&data_a);
        let sb = sketch_hex(&data_b);
        let dist = hamming_distance_hex(&sa, &sb).expect("valid sketches");
        // Genuinely unrelated data → distance near 128 (half of 256 bits).
        assert!(
            dist > 80,
            "unrelated files produced Hamming distance {dist}, expected > 80"
        );
    }

    /// Streaming (multiple updates) must match one-shot for the same data.
    #[test]
    fn test_streaming_matches_oneshot() {
        let data: Vec<u8> = (0..150_000u32).map(|i| (i % 251) as u8).collect();

        let oneshot = sketch_hex(&data);

        let mut builder = SketchBuilder::new();
        for chunk in data.chunks(4_096) {
            builder.update(chunk);
        }
        let streamed = hex::encode(builder.finalize());

        assert_eq!(oneshot, streamed, "streaming sketch must match one-shot");
    }

    /// Two versions of a file (small in-place modification) should produce
    /// a small Hamming distance. This is the primary use case: file v2
    /// differs from v1 in a small section, and the sketch should reflect
    /// that similarity so future reference-selection logic can find v1 as
    /// a good delta baseline for v2.
    #[test]
    fn test_file_versions_similar() {
        let base: Vec<u8> = (0..200_000u32).map(|i| (i % 256) as u8).collect();
        let mut v2 = base.clone();
        // Modify 200 bytes in the middle (e.g. a config section changed).
        for b in &mut v2[100_000..100_200] {
            *b ^= 0xFF;
        }

        let s1 = sketch_hex(&base);
        let s2 = sketch_hex(&v2);
        let dist = hamming_distance_hex(&s1, &s2).expect("valid sketches");
        // Only 1-2 chunks differ (the ones containing the modified bytes).
        // With ~25 chunks, that's <10% of votes → small sign-bit flips.
        assert!(
            dist < 40,
            "small in-place modification produced Hamming distance {dist}, expected < 40"
        );
    }

    /// Empty input produces a valid (deterministic) sketch.
    #[test]
    fn test_empty_input() {
        let s = sketch_hex(&[]);
        // 64 hex chars, all zeros (no chunks → all accumulators are 0 → sign is 0).
        assert_eq!(s.len(), 64);
        assert_eq!(s, "0".repeat(64));
    }

    /// Very small input (< CDC_MIN) still produces a valid sketch (one chunk).
    #[test]
    fn test_small_input() {
        let data = vec![1, 2, 3, 4, 5];
        let s = sketch_hex(&data);
        assert_eq!(s.len(), 64);
        // Non-empty input must produce a non-zero sketch.
        assert_ne!(s, "0".repeat(64));
    }

    /// `is_similar_hex` convenience function.
    #[test]
    fn test_is_similar() {
        let data = vec![0x42u8; 100_000];
        let s = sketch_hex(&data);
        assert!(is_similar_hex(&s, &s, SIMILARITY_THRESHOLD_BITS));

        let other = sketch_hex(&[0x99u8; 100_000]);
        assert!(!is_similar_hex(&s, &other, SIMILARITY_THRESHOLD_BITS));
    }

    /// `hamming_distance_hex` returns None for invalid hex.
    #[test]
    fn test_invalid_hex() {
        assert_eq!(hamming_distance_hex("nothex", "alsonot"), None);
        assert_eq!(hamming_distance_hex("deadbeef", "cafe"), None); // different lengths
    }

    /// The gear table must be non-degenerate (not all zeros).
    #[test]
    fn test_gear_table_nonzero() {
        let zeros = GEAR.iter().filter(|&&v| v == 0).count();
        assert_eq!(zeros, 0, "gear table must have no zero entries");
    }

    /// `sketch_file_hex` matches `sketch_hex` for the same bytes.
    #[test]
    fn test_sketch_file_matches_bytes() {
        use std::io::Write;
        let data: Vec<u8> = (0..50_000u32).map(|i| (i % 211) as u8).collect();

        let mut tmp = tempfile::NamedTempFile::new().unwrap();
        tmp.write_all(&data).unwrap();
        tmp.flush().unwrap();

        let from_file = sketch_file_hex(tmp.path()).unwrap();
        let from_bytes = sketch_hex(&data);
        assert_eq!(from_file, from_bytes);
    }

    /// Determinism: same input always produces the same sketch.
    #[test]
    fn test_deterministic() {
        let data: Vec<u8> = (0..1000).map(|i| (i * 7 % 256) as u8).collect();
        let s1 = sketch_hex(&data);
        let s2 = sketch_hex(&data);
        assert_eq!(s1, s2);
    }
}

// ── Proptests ─────────────────────────────────────────────────────────

#[cfg(test)]
mod proptests {
    use super::*;
    use proptest::prelude::*;

    proptest! {
        /// Identical data → Hamming distance 0, always.
        #[test]
        fn prop_identical_zero_distance(data in prop::collection::vec(any::<u8>(), 0..50_000)) {
            let s = sketch_hex(&data);
            prop_assert_eq!(hamming_distance_hex(&s, &s), Some(0));
        }

        /// Sketch is always 64 hex chars (256 bits).
        #[test]
        fn prop_sketch_length(data in prop::collection::vec(any::<u8>(), 0..50_000)) {
            let s = sketch_hex(&data);
            prop_assert_eq!(s.len(), 64);
        }

        /// Streaming == one-shot for arbitrary chunk sizes.
        #[test]
        fn prop_streaming_matches_oneshot(
            data in prop::collection::vec(any::<u8>(), 0..50_000),
            chunk_size in 1usize..=4096,
        ) {
            let oneshot = sketch_hex(&data);
            let mut builder = SketchBuilder::new();
            for chunk in data.chunks(chunk_size) {
                builder.update(chunk);
            }
            let streamed = hex::encode(builder.finalize());
            prop_assert_eq!(oneshot, streamed);
        }

        /// Hamming distance is symmetric: d(a,b) == d(b,a).
        #[test]
        fn prop_hamming_symmetric(
            a in prop::collection::vec(any::<u8>(), 1_000..50_000),
            b in prop::collection::vec(any::<u8>(), 1_000..50_000),
        ) {
            let sa = sketch_hex(&a);
            let sb = sketch_hex(&b);
            let d_ab = hamming_distance_hex(&sa, &sb).unwrap();
            let d_ba = hamming_distance_hex(&sb, &sa).unwrap();
            prop_assert_eq!(d_ab, d_ba);
        }

        /// A single byte flip in a large enough file should produce a
        /// small Hamming distance (CDC re-syncs within a few chunks,
        /// and with many chunks the changed votes are a small fraction).
        #[test]
        fn prop_small_change_small_distance(
            base in prop::collection::vec(any::<u8>(), 100_000..200_000),
            flip_pos in 0usize..200_000,
        ) {
            if flip_pos >= base.len() {
                return Ok(());
            }
            let mut modified = base.clone();
            let idx = flip_pos % modified.len();
            modified[idx] ^= 0xFF;
            let s_base = sketch_hex(&base);
            let s_mod = sketch_hex(&modified);
            let dist = hamming_distance_hex(&s_base, &s_mod).unwrap();
            // With ~25 chunks (200KB / 8KB avg), a single byte flip
            // affects ~2-3 chunks. The sign-bit flips are bounded by
            // the fraction of changed votes (~10%).
            prop_assert!(dist <= 80, "single byte flip distance {} > 80", dist);
        }
    }
}
