apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: beshu-tech-runner-set
  namespace: arc-systems
spec:
  replicas: 4
  selector:
    matchLabels:
      app: beshu-tech-runner
  serviceName: beshu-tech-runner
  template:
    metadata:
      labels:
        app: beshu-tech-runner
    spec:
      containers: []
  labels:
    - self-hosted
    - linux
    - x64
    - k3s
  organization: beshu-tech
  group: Default
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
