// SPDX-License-Identifier: BUSL-1.1

//! Section-level admin config API (Wave 1 of the admin UI revamp).
//!
//! Provides section-scoped GET / PUT / validate endpoints:
//!
//! - `GET  /api/admin/config/section/:name[?format=yaml]`
//!   Returns the one named section (`admission` / `access` / `storage` /
//!   `advanced`) of the runtime config, with secrets redacted. JSON by
//!   default; `?format=yaml` emits the canonical YAML for that section only.
//! - `PUT  /api/admin/config/section/:name`
//!   Partial update: accepts JSON for the named section and replaces the
//!   corresponding slice of the in-memory [`Config`]. Routes through the
//!   shared [`super::apply_config_transition`] helper so field-level PATCH,
//!   document-level APPLY, and section-level PUT are all one transition
//!   story.
//! - `POST /api/admin/config/section/:name/validate`
//!   Dry-run variant: parses + validates the section body, computes the
//!   would-be diff, returns `{ok, warnings[], diff}`. No state change.
//!
//! The wire shape for each section is exactly the in-memory type in
//! [`crate::config_sections`] (`AdmissionSection`, `AccessSection`,
//! `StorageSection`, `AdvancedSection`) — so the UI's JSON schema is the
//! same one generated by `schemars` for the YAML view. One schema drives
//! both surfaces.
//!
//! ## Why this layer exists
//!
//! The UI revamp (`docs/plan/admin-ui-revamp.md` §6) needs a scope between
//! the existing *field-level* PATCH (which takes an ad-hoc flat JSON that
//! doesn't match the YAML document) and the *document-level* APPLY (which
//! requires the operator to ship a full canonical YAML even to edit one
//! toggle). The section API gives the UI a natural atomic unit — "apply
//! my Admission section edits, leave Access / Storage / Advanced alone" —
//! while keeping the same hot-reload + persist semantics as the full-
//! document path.

use crate::api::admin::extract::{AdminJson, AdminQuery};
use axum::extract::{Path, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::Json;
use serde::{Deserialize, Serialize};
use std::sync::Arc;

use super::super::{AdminError, AdminState};
use super::write::{
    self, Built, ConfigWrite, EnvRefs, Mode, Outcome, Rejection, ScrubEnv, Stage, Surface,
    WriteResult,
};
use super::{unknown_section_error, SectionName};
use crate::config_sections::{AdmissionSection, SectionedConfig};

/// Query params for the section GET endpoint.
#[derive(Deserialize, Default)]
pub struct SectionGetQuery {
    /// `"yaml"` to return canonical YAML for this section. Omitted /
    /// anything else returns JSON.
    #[serde(default)]
    format: Option<String>,
}

/// Response body for section PUT + validate.
///
/// Mirrors [`super::ConfigValidateResponse`] in spirit but carries a diff
/// list — the UI renders this inside the plan → diff → apply dialog
/// described in the revamp plan §5.3.
#[derive(Serialize)]
pub struct SectionApplyResponse {
    /// `true` when the section was applied (PUT) or would apply cleanly
    /// (validate). `false` when validation rejected the body; the `error`
    /// field carries the reason.
    pub ok: bool,
    /// Human-readable warnings — same contract as the field-level PATCH:
    /// the HTTP status stays 200 and warnings narrate any partial / best-
    /// effort outcomes (invalid log_level, IAM-mode-gated legacy creds,
    /// etc.). Rendered in the Apply dialog above the confirm button.
    ///
    /// Only the warnings THIS change introduces; the ones the current config
    /// already produces are in `existing_warnings`.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub warnings: Vec<String>,
    /// Advisory warnings the current config already produces, unchanged by
    /// this apply. The Apply dialog folds them away so they do not drown the
    /// warnings that matter for this change (issue #92).
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub existing_warnings: Vec<String>,
    /// `true` when at least one field in the transition is in the restart-
    /// required set (see `apply_config_transition`). The UI surfaces this
    /// as a banner in the Apply dialog so operators don't ship a
    /// restart-requiring change during a busy window without noticing.
    pub requires_restart: bool,
    /// Only set on PUT success — path the persisted YAML was written to.
    /// Absent for dry-run (validate) responses.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persisted_path: Option<String>,
    /// Machine-readable error string when `ok: false`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// JSON Merge Patch showing what would change relative to the current
    /// runtime config, scoped to the submitted section. The UI renders it
    /// in the Apply dialog as a side-by-side diff (§5.3 of the plan).
    ///
    /// The structure is `{ section_name: { field_path: {before, after} } }`
    /// — a shallow per-field diff, not a full structural diff. That's
    /// enough for the UI's "cache_size_mb: 256 → 2048" view; deeper diffs
    /// (e.g. which bucket entry changed) are shown by the richer section
    /// editors directly, not by this endpoint.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub diff: Option<serde_json::Value>,
}

/// Build an early-return rejection response for the section endpoints.
/// Encodes the "always-pair a status code with a SectionApplyResponse
/// carrying an error message" pattern that repeated ~8× across
/// `get_section` + `apply_section` — the boilerplate now lives here
/// so handler bodies focus on what changed between failure cases.
///
/// `warnings` and `diff` default to empty/None, which fits most reject
/// sites; the handful of sites that want to carry validation warnings
/// or a precomputed diff through still build the response inline.
fn reject(status: StatusCode, error: impl Into<String>) -> Response {
    (
        status,
        Json(SectionApplyResponse {
            ok: false,
            existing_warnings: Vec::new(),
            warnings: vec![],
            requires_restart: false,
            persisted_path: None,
            error: Some(error.into()),
            diff: None,
        }),
    )
        .into_response()
}

/// `GET /api/admin/config/section/:name` — serialize the named slice of
/// the runtime config.
///
/// JSON by default (matches the shape the UI's form controllers expect).
/// `?format=yaml` emits the canonical YAML for that one section — useful
/// for the per-section Copy-as-YAML button described in §3.3 of the plan.
/// Secrets are redacted via the same [`Config::redact_all_secrets`](crate::config::Config::redact_all_secrets) used
/// by the document-level export.
pub async fn get_section(
    State(state): State<Arc<AdminState>>,
    Path(name): Path<String>,
    AdminQuery(query): AdminQuery<SectionGetQuery>,
) -> impl IntoResponse {
    let Some(section) = SectionName::parse(&name) else {
        return reject(StatusCode::NOT_FOUND, unknown_section_error(&name));
    };

    let cfg = state.config.read().await;
    let redacted = cfg.redact_all_secrets();
    let version = super::version::config_version(&cfg, Some(section));
    let sectioned = SectionedConfig::from_flat(&redacted);
    drop(cfg);

    let yaml_format = query.format.as_deref() == Some("yaml");

    let mut resp = match section {
        SectionName::Admission => emit_section(
            section,
            sectioned.admission.unwrap_or_default(),
            yaml_format,
        ),
        SectionName::Access => emit_section(section, sectioned.access, yaml_format),
        SectionName::Storage => emit_section(section, sectioned.storage, yaml_format),
        SectionName::Advanced => emit_section(section, sectioned.advanced, yaml_format),
    }
    .unwrap_or_else(IntoResponse::into_response);
    // The version a PUT sends back in `If-Match` (optimistic concurrency).
    resp.headers_mut()
        .insert(axum::http::header::ETAG, super::version::etag(&version));
    resp
}

/// Serialize one section in the requested format. Factored out so
/// [`get_section`] stays one match arm per section — the generic makes
/// the format branch uniform.
fn emit_section<T: serde::Serialize>(
    section: SectionName,
    value: T,
    yaml_format: bool,
) -> Result<Response, AdminError> {
    if yaml_format {
        // Emit `<name>:\n  ...fields...` — matches the shape this same
        // block would take inside the full canonical YAML. The empty-
        // section case (e.g. `admission:` with no blocks) is normal
        // and not an error; the client renders an editor seeded with
        // the section's defaults.
        let mut map = serde_yaml::Mapping::new();
        let yaml_err = |e: serde_yaml::Error| {
            AdminError::internal(format!("failed to serialize section to YAML: {}", e))
        };
        let value_yaml = serde_yaml::to_value(&value).map_err(yaml_err)?;
        map.insert(
            serde_yaml::Value::String(section.as_str().to_string()),
            value_yaml,
        );
        let doc = serde_yaml::Value::Mapping(map);
        let s = serde_yaml::to_string(&doc).map_err(yaml_err)?;
        Ok((
            StatusCode::OK,
            [(axum::http::header::CONTENT_TYPE, "application/yaml")],
            s,
        )
            .into_response())
    } else {
        Ok((StatusCode::OK, Json(value)).into_response())
    }
}

/// `PUT /api/admin/config/section/:name` — apply a section partial.
///
/// Body is JSON matching the target section's shape (the same type used
/// by the YAML serializer — no ad-hoc wrapper), applied as an RFC 7396
/// merge patch on the running config's section. The handler builds the
/// incoming config (project → merge → `into_flat`, which runs the YAML
/// loader's `normalize` + admission validation); the shared write pipeline
/// (`super::write`) does the rest under one write lock: If-Match, secret
/// preservation, env overrides, checks and gates, transition, persist.
///
/// The result's `diff` field shows exactly what changed relative to the
/// pre-PUT state so the Apply dialog can display it.
pub async fn put_section(
    State(state): State<Arc<AdminState>>,
    Path(name): Path<String>,
    headers: HeaderMap,
    body: AdminJson<serde_json::Value>,
) -> impl IntoResponse {
    section_write(&state, &name, &body.0, Mode::Apply, Some(&headers)).await
}

/// `POST /api/admin/config/section/:name/validate` — dry-run a section apply.
///
/// Same inputs and the same pipeline steps as PUT, but no state change and
/// no persist. Returns `ok`, the computed diff, and warnings. The UI calls
/// this when the operator presses Apply: the diff is rendered in the
/// confirmation modal, and a second click fires the real PUT.
pub async fn validate_section(
    State(state): State<Arc<AdminState>>,
    Path(name): Path<String>,
    body: AdminJson<serde_json::Value>,
) -> impl IntoResponse {
    section_write(&state, &name, &body.0, Mode::DryRun, None).await
}

/// Shared body of PUT + validate: build the incoming config, run the write
/// pipeline, shape the response.
async fn section_write(
    state: &Arc<AdminState>,
    name: &str,
    body: &serde_json::Value,
    mode: Mode,
    headers: Option<&HeaderMap>,
) -> Response {
    let Some(section) = SectionName::parse(name) else {
        return reject(StatusCode::NOT_FOUND, unknown_section_error(name));
    };
    let no_env = EnvRefs::new();
    let write = ConfigWrite {
        surface: Surface::Section { section, body },
        mode,
        headers,
        extra_env: &no_env,
    };
    let result = write::run(state, write, |old| {
        let invalid = |e: String| Rejection::new(Stage::Build, StatusCode::BAD_REQUEST, e);
        // Project → replace one slice → collapse back. The body is "the new
        // non-secret state of this section"; the pipeline merges secrets.
        let mut sectioned = SectionedConfig::from_flat(old);
        merge_patch_section(&mut sectioned, section, body).map_err(invalid)?;
        let incoming = sectioned.into_flat().map_err(invalid)?;
        Ok(Built {
            incoming,
            warnings: Vec::new(),
        })
    })
    .await;
    shape_section(section, result)
}

/// The section PUT / validate body of a write outcome.
fn shape_section(section: SectionName, result: WriteResult) -> Response {
    let WriteResult { outcome, refs } = result;
    match outcome {
        Outcome::Conflict { current } => {
            super::version::conflict(&current, &format!("'{}' section", section.as_str()))
        }
        Outcome::Rejected(r) => {
            let w = *r.warnings;
            let (error, warnings, existing, diff) = match r.stage {
                Stage::Transition => (
                    format!(
                        "Failed to apply section '{}' (no state changed): {}",
                        section.as_str(),
                        r.error
                    ),
                    [w.preserve, w.env, w.check_new].concat(),
                    w.existing,
                    r.diff,
                ),
                // The secret-preservation and env warnings ride along.
                Stage::Normalize | Stage::Check | Stage::Gate => {
                    (r.error, [w.preserve, w.env].concat(), Vec::new(), None)
                }
                _ => (r.error, Vec::new(), Vec::new(), None),
            };
            let body = SectionApplyResponse {
                ok: false,
                warnings,
                existing_warnings: existing,
                requires_restart: false,
                persisted_path: None,
                error: Some(error),
                diff,
            };
            write::respond(r.status, body, &refs, None)
        }
        Outcome::Validated {
            warnings: w,
            requires_restart,
            diff,
        } => {
            let body = SectionApplyResponse {
                ok: true,
                warnings: [w.preserve, w.env, w.check_new, w.preview].concat(),
                existing_warnings: w.existing,
                requires_restart,
                persisted_path: None,
                error: None,
                diff,
            };
            write::respond(StatusCode::OK, body, &refs, None)
        }
        Outcome::Applied {
            warnings: w,
            requires_restart,
            diff,
            persist,
            version,
        } => {
            // The persist outcome is the HTTP status (200 vs. 500) plus the
            // warning text; there is no separate `persisted` field here.
            let (persisted_path, status, persist_warning) = match persist {
                Ok(path) => (Some(path), StatusCode::OK, None),
                Err((path, e)) => (
                    None,
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Some(format!(
                        "Applied section '{}' in memory but FAILED to persist to {}: {}. Server \
                         will revert on next restart — fix the IO and re-apply.",
                        section.as_str(),
                        path,
                        e
                    )),
                ),
            };
            let body = SectionApplyResponse {
                ok: true,
                warnings: [w.preserve, w.env, w.check_new, w.transition]
                    .concat()
                    .into_iter()
                    .chain(persist_warning)
                    .collect(),
                existing_warnings: w.existing,
                requires_restart,
                persisted_path,
                error: None,
                diff,
            };
            let etag = super::version::etag(&version);
            write::respond(status, body, &refs, Some(etag))
        }
    }
}

impl ScrubEnv for SectionApplyResponse {
    fn scrub_env(&mut self, refs: &EnvRefs) {
        write::scrub_strings(
            self.warnings
                .iter_mut()
                .chain(&mut self.existing_warnings)
                .chain(&mut self.error),
            refs,
        );
        if let Some(diff) = self.diff.as_mut() {
            diff.scrub_env(refs);
        }
    }
}

/// Apply a JSON-Merge-Patch (RFC 7396) body on top of one section of
/// a `SectionedConfig`.
///
/// ## Why merge, not replace
///
/// A naïve "replace the whole section" semantic is a serious foot-gun
/// for the UI's section PUT: the operator edits one field in the
/// admin form (say, `advanced.max_delta_ratio`), the client sends
/// `{max_delta_ratio: 0.42}`, and the server silently resets every
/// OTHER advanced field to its compile-time default because they
/// were absent from the body. We observed this live in local browser
/// testing against v0.8.0 — one edit zeroed `cache_size_mb`,
/// `listen_addr`, and `log_level`.
///
/// RFC 7396 JSON Merge Patch is the right semantic for partial
/// updates:
///   * Keys present in body -> apply (replace-in-place at that key).
///   * Keys absent from body -> keep the old value.
///   * Keys set to `null` in body -> delete / fall back to default.
///
/// List-valued fields like `admission.blocks` are atomic leaves
/// (present-or-absent, no per-index merge); sending `{blocks: []}`
/// clears the chain. Map-valued fields like `storage.buckets` are
/// merged entry-by-entry (per-bucket null deletes that bucket,
/// other buckets stay untouched).
///
/// ## Implementation
///
/// Each arm projects the current section to JSON via
/// [`merge_into_typed`], applies the merge patch, and deserializes
/// back. Structural errors (unknown fields, bad types) surface
/// through serde the same way they would with replace semantics.
/// The match is exhaustive on [`SectionName`] so adding a fifth
/// section breaks this file noisily until every branch is updated.
fn merge_patch_section(
    sectioned: &mut SectionedConfig,
    section: SectionName,
    body: &serde_json::Value,
) -> Result<(), String> {
    match section {
        SectionName::Admission => {
            // Admission's `Option<AdmissionSection>` lives in the
            // sectioned shape, but at merge time we project the inner
            // `AdmissionSection` (default when `None`). After merge,
            // collapse back to `None` when blocks are empty so the
            // emitted YAML stays minimal.
            let current = sectioned.admission.clone().unwrap_or_default();
            let merged: AdmissionSection = merge_into_typed(&current, body, "admission")?;
            sectioned.admission = if merged.blocks.is_empty() {
                None
            } else {
                Some(merged)
            };
        }
        SectionName::Access => {
            sectioned.access = merge_into_typed(&sectioned.access, body, "access")?;
        }
        SectionName::Storage => {
            sectioned.storage = merge_into_typed(&sectioned.storage, body, "storage")?;
        }
        SectionName::Advanced => {
            sectioned.advanced = merge_into_typed(&sectioned.advanced, body, "advanced")?;
        }
    }
    Ok(())
}

/// Merge a JSON patch onto a typed section value and re-deserialize.
///
/// `current` is projected to JSON, the patch is applied in-place per
/// RFC 7396, and the result is parsed back into `T`. Error messages
/// are scoped by `label` (`"admission"`, `"access"`, …) so the
/// serde diagnostic the operator sees names the right section.
///
/// The generic bound is `Serialize + DeserializeOwned` and nothing
/// else; every section type in [`crate::config_sections`] satisfies
/// it. Keeps the four arms of [`merge_patch_section`] free of copy-
/// paste — mutating a section now means adding one line, not five.
fn merge_into_typed<T>(
    current: &T,
    patch: &serde_json::Value,
    label: &'static str,
) -> Result<T, String>
where
    T: serde::Serialize + serde::de::DeserializeOwned,
{
    let mut merged = serde_json::to_value(current)
        .map_err(|e| format!("internal: failed to project {} section: {}", label, e))?;
    apply_merge_patch(&mut merged, patch);
    // Deserialize with field-path tracking so a type error names the exact
    // offending field ("buckets.beshu-b2.public_prefixes: invalid type …")
    // instead of a path-less serde message the operator can't act on.
    serde_path_to_error::deserialize(merged).map_err(|e| {
        let path = e.path().to_string();
        let inner = e.into_inner();
        if path == "." {
            format!("invalid {label} section body: {inner}")
        } else {
            format!("invalid {label} section body at `{path}`: {inner}")
        }
    })
}

/// Apply a JSON Merge Patch (RFC 7396) in-place to `target`.
///
/// The algorithm is short enough to inline rather than pull in an
/// external crate. Per the spec (`MergePatch(Target, Patch)`):
///
///   * If `patch` is an object: a non-object target is first replaced
///     with `{}` (the spec treats it as undefined), then each patch key
///     recurses — `null` removes the key, anything else merges.
///   * Otherwise `patch` replaces `target` wholesale (arrays atomic).
///
/// The recursion on ABSENT keys is load-bearing: a `null` nested inside
/// a newly-inserted subtree means "remove" and must be DROPPED, never
/// inserted verbatim (a surviving null then fails typed deserialization
/// — the `public_prefixes: null` → "expected a sequence" incident).
fn apply_merge_patch(target: &mut serde_json::Value, patch: &serde_json::Value) {
    if let serde_json::Value::Object(patch_map) = patch {
        if !target.is_object() {
            *target = serde_json::Value::Object(serde_json::Map::new());
        }
        let target_map = target
            .as_object_mut()
            .expect("target coerced to object above");
        for (k, v) in patch_map {
            if v.is_null() {
                target_map.remove(k);
            } else {
                let slot = target_map
                    .entry(k.clone())
                    .or_insert(serde_json::Value::Null);
                apply_merge_patch(slot, v);
            }
        }
    } else {
        *target = patch.clone();
    }
}

/// Compute the per-field diff for one section.
///
/// Semantics: project both configs into a `SectionedConfig`, pick the
/// named section off each, run a shallow recursive diff on the two
/// JSON representations, and return
/// `{ "<section>": { "<path>": {"before": ..., "after": ...} } }`.
///
/// The diff intentionally collapses equal values — the UI only wants to
/// render what changed. For Admission, the blocks list is diffed by
/// name so reorders surface as a single pair of before/after lists
/// rather than N spurious per-index changes. (Other sections are
/// scalar-heavy so per-field is enough.)
/// Map a secret's plaintext to a deterministic, non-reversible
/// placeholder suitable for the Apply-dialog diff. Preserved secrets
/// compare equal (same fingerprint); rotations show a readable
/// swap (`fp:abc12345…` → `fp:def67890…`) without leaking material.
///
/// Used for per-backend encryption `key` and `legacy_key` on the
/// storage section diff (see `inject_encryption_fingerprints`). The
/// SigV4 pair and backend creds are handled by `redact_all_secrets`
/// which nulls them — they don't rotate through this endpoint.
///
/// 8-hex-char truncation is enough to distinguish rotations
/// practically; the full SHA-256 is needlessly long in the UI.
fn fingerprint_secret(plaintext: Option<&str>) -> Option<String> {
    plaintext.map(|pt| {
        use sha2::{Digest, Sha256};
        let digest = Sha256::digest(pt.as_bytes());
        format!("fp:{}", hex::encode(&digest[..4]))
    })
}

/// Project a config for the Apply-dialog diff: every secret becomes a
/// deterministic fingerprint (`fp:xxxxxxxx`) instead of being NULLED, so
/// rotations SURFACE in the diff instead of vanishing. The old behaviour
/// redacted both sides with `redact_all_secrets`, which nulls credentials
/// on both sides — a credentials change produced an empty diff and the
/// Apply dialog claimed "No changes detected" for an apply that very much
/// changed them. Fingerprints fix that: unchanged secrets compare equal,
/// rotations show `fp:a → fp:b`, nothing leaks (one-way truncated hash).
/// `${env:NAME}` references stay readable verbatim; identifiers
/// (access_key_id) stay plaintext — operators must see WHICH key rotated.
fn fingerprint_secrets_for_diff(cfg: &crate::config::Config) -> crate::config::Config {
    fn fp_str(s: &str) -> String {
        if crate::config::is_env_ref(s) {
            s.to_string()
        } else {
            fingerprint_secret(Some(s)).expect("input is Some")
        }
    }
    fn fp_opt(o: &mut Option<String>) {
        if let Some(v) = o {
            *v = fp_str(v);
        }
    }
    fn fp_enc(enc: &mut crate::config::BackendEncryptionConfig) {
        use crate::config::BackendEncryptionConfig as E;
        match enc {
            E::None { legacy_key, .. } => fp_opt(legacy_key),
            E::Aes256GcmProxy {
                key, legacy_key, ..
            } => {
                fp_opt(key);
                fp_opt(legacy_key);
            }
            E::SseKms { legacy_key, .. } => fp_opt(legacy_key),
            E::SseS3 { legacy_key, .. } => fp_opt(legacy_key),
        }
    }
    let mut out = cfg.clone();
    out.bootstrap_password_hash = None; // never diffed (dedicated endpoint)
    fp_opt(&mut out.secret_access_key);
    if let crate::config::BackendConfig::S3 {
        ref mut secret_access_key,
        ..
    } = out.backend
    {
        fp_opt(secret_access_key);
    }
    fp_enc(&mut out.backend_encryption);
    for nb in &mut out.backends {
        if let crate::config::BackendConfig::S3 {
            ref mut secret_access_key,
            ..
        } = nb.backend
        {
            fp_opt(secret_access_key);
        }
        fp_enc(&mut nb.encryption);
    }
    for u in &mut out.iam_users {
        if !u.secret_access_key.is_empty() {
            u.secret_access_key = fp_str(&u.secret_access_key);
        }
    }
    for pr in &mut out.auth_providers {
        fp_opt(&mut pr.client_secret);
    }
    for v in out.event_delivery.webhook_headers.values_mut() {
        *v = fp_str(v);
    }
    fp_opt(&mut out.event_delivery.slack_bot_token);
    if out.event_delivery.format == crate::config_sections::EventDeliveryFormat::Slack
        && !out.event_delivery.uses_slack_bot_token()
    {
        fp_opt(&mut out.event_delivery.webhook_url);
        for url in out.event_delivery.webhook_urls.iter_mut() {
            *url = fp_str(url);
        }
    }
    out
}

pub(super) fn compute_section_diff(
    section: SectionName,
    old_cfg: &crate::config::Config,
    new_cfg: &crate::config::Config,
) -> serde_json::Value {
    // Redact BOTH sides. If only one side is redacted the diff
    // spuriously "changes" a preserved credential to a placeholder
    // (or vice versa) and the client surfaces it in the Apply
    // dialog — operators would see "password changed" on a plain
    // `advanced.max_delta_ratio` edit. Redacting both means secrets
    // either compare-equal (preserved) or both appear as the same
    // redaction placeholder.
    //
    // Per-backend encryption keys (primary + legacy shim) need
    // special handling: `redact_all_secrets` nulls them on BOTH
    // sides, which hides real rotations. We fingerprint them
    // instead — each plaintext maps to a deterministic-but-non-
    // reversible `fp:xxxxxxxx` placeholder so:
    //   * unchanged keys compare equal (no spurious diff).
    //   * rotations surface as a readable `fp:a→fp:b` swap.
    //   * neither side leaks key material (one-way hash truncated
    //     to 8 hex chars, matching the pre-refactor behaviour).
    let old_fp = fingerprint_secrets_for_diff(old_cfg);
    let new_fp = fingerprint_secrets_for_diff(new_cfg);

    let old_sectioned = SectionedConfig::from_flat(&old_fp);
    let new_sectioned = SectionedConfig::from_flat(&new_fp);

    let (old_json, new_json) = match section {
        SectionName::Admission => (
            serde_json::to_value(old_sectioned.admission.unwrap_or_default()).unwrap_or_default(),
            serde_json::to_value(new_sectioned.admission.unwrap_or_default()).unwrap_or_default(),
        ),
        SectionName::Access => (
            serde_json::to_value(old_sectioned.access).unwrap_or_default(),
            serde_json::to_value(new_sectioned.access).unwrap_or_default(),
        ),
        SectionName::Storage => (
            serde_json::to_value(old_sectioned.storage).unwrap_or_default(),
            serde_json::to_value(new_sectioned.storage).unwrap_or_default(),
        ),
        SectionName::Advanced => (
            serde_json::to_value(old_sectioned.advanced).unwrap_or_default(),
            serde_json::to_value(new_sectioned.advanced).unwrap_or_default(),
        ),
    };

    let mut diff = serde_json::Map::new();
    shallow_diff("", &old_json, &new_json, &mut diff);

    let mut out = serde_json::Map::new();
    out.insert(
        section.as_str().to_string(),
        serde_json::Value::Object(diff),
    );
    serde_json::Value::Object(out)
}

/// How one field appears in the raw PUT body: absent, `null`, or a value.
/// After merge-patch / serde, absent and `null` both read as `None`; this
/// keeps them apart.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Presence {
    #[default]
    Absent,
    Null,
    Set,
}

impl Presence {
    fn of(obj: &serde_json::Map<String, serde_json::Value>, field: &str) -> Self {
        match obj.get(field) {
            None => Self::Absent,
            Some(serde_json::Value::Null) => Self::Null,
            Some(_) => Self::Set,
        }
    }
}

/// THE merge rule for a kept encryption field (`key`, `key_id`,
/// `legacy_key`): absent keeps the old value, an explicit `null` clears
/// it, a value replaces it. Returns true when the old value was restored.
pub(crate) fn merge_kept_field(
    presence: Presence,
    new: &mut Option<String>,
    old: Option<&str>,
) -> bool {
    if presence == Presence::Absent && new.is_none() && old.is_some() {
        *new = old.map(str::to_string);
        return true;
    }
    false
}

/// What the operator said about each kept encryption field for one
/// backend, from the raw PUT body. The fields are independent: a PATCH
/// that sets `key: null` and leaves `legacy_key` absent clears the
/// primary but keeps the old shim.
#[derive(Debug, Default, Clone, Copy)]
pub(crate) struct BackendKeyPresence {
    pub key: Presence,
    pub key_id: Presence,
    pub legacy_key: Presence,
}

/// Inspects a section-PUT body and reports, per backend-encryption
/// entry, whether each of `key` / `legacy_key` is present-as-null in
/// the raw JSON. After merge-patch these both collapse to None on
/// the flat `Config`; the probe recovers the distinction so
/// preservation can correctly distinguish "preserve" from
/// "explicitly clear".
pub(crate) struct BackendEncryptionKeyProbe {
    singleton: BackendKeyPresence,
    /// Per-backend-name probe results. `HashMap` keyed by backend
    /// name — matches the way preserve_backend_encryption_secrets
    /// walks the list.
    named: std::collections::HashMap<String, BackendKeyPresence>,
}

impl BackendEncryptionKeyProbe {
    /// Probe the raw section body. Only the `Storage` section carries
    /// encryption fields; others return empty probes (no-op preservation
    /// rules).
    pub(crate) fn from_section(section: SectionName, body: &serde_json::Value) -> Self {
        let mut singleton = BackendKeyPresence::default();
        let mut named: std::collections::HashMap<String, BackendKeyPresence> =
            std::collections::HashMap::new();
        if matches!(section, SectionName::Storage) {
            if let Some(obj) = body.as_object() {
                // Singleton: storage.backend_encryption
                if let Some(be) = obj.get("backend_encryption") {
                    singleton = probe_enc_body(be);
                }
                // List: storage.backends[] — each with a `name` and
                // optional `encryption` object.
                if let Some(arr) = obj.get("backends").and_then(|v| v.as_array()) {
                    for entry in arr {
                        if let Some(name) = entry
                            .get("name")
                            .and_then(|v| v.as_str())
                            .map(|s| s.to_string())
                        {
                            if let Some(enc) = entry.get("encryption") {
                                named.insert(name, probe_enc_body(enc));
                            }
                        }
                    }
                }
            }
        }
        Self { singleton, named }
    }

    pub(crate) fn for_singleton(&self) -> BackendKeyPresence {
        self.singleton
    }

    pub(crate) fn for_named(&self, name: &str) -> BackendKeyPresence {
        self.named.get(name).copied().unwrap_or_default()
    }
}

/// Probe a single `encryption: {...}` object for explicit-null key
/// fields. Missing object → both flags false (preservation default).
fn probe_enc_body(enc: &serde_json::Value) -> BackendKeyPresence {
    let obj = match enc.as_object() {
        Some(m) => m,
        None => return BackendKeyPresence::default(),
    };
    BackendKeyPresence {
        key: Presence::of(obj, "key"),
        key_id: Presence::of(obj, "key_id"),
        legacy_key: Presence::of(obj, "legacy_key"),
    }
}

/// Preserve encryption key material on a single backend entry
/// across a section PUT or a document apply.
///
/// Semantics for each of `key` / `legacy_key`:
///   * body absent, new==None → restore from old (preserve).
///   * body null, new==None → leave None (explicit clear).
///   * new==Some → operator rotated; validate hex, keep as-is.
///
/// A proxy key that goes out of use (rotation to a new key, or a mode
/// flip away from `aes256-gcm-proxy`) moves into the decrypt-only
/// `legacy_key` slot, with the id the objects carry, unless the body
/// sets `legacy_key` itself or nulls it. The objects written under
/// that key stay readable, and the re-encrypt job can rewrite them.
///
/// Errors when the change would lose a key that objects can still
/// need: a rotation that keeps the same key id (old objects would be
/// decrypted with the new key), or a rotation while the one legacy
/// slot already holds a different key.
///
/// `backend_name` feeds the key-id derivation (`"default"` for the
/// singleton backend, as in the engine).
pub(crate) fn preserve_backend_encryption_secrets(
    backend_name: &str,
    new: &mut crate::config::BackendEncryptionConfig,
    old: &crate::config::BackendEncryptionConfig,
    probe: BackendKeyPresence,
) -> Result<(), String> {
    use crate::config::BackendEncryptionConfig as E;
    // H8: validate hex during preservation. If the old config landed
    // in memory with malformed hex (e.g. a pre-existing pathological
    // state from a prior load that only warned, not errored), DON'T
    // propagate that into the new config — the subsequent
    // `rebuild_engine → wrap_backend_with_encryption →
    // EncryptionKey::from_hex` would 5xx on a PATCH that touched an
    // unrelated field. Silently skip preservation for unparseable
    // old keys; the engine's warn-level "no key configured" diagnostic
    // will surface the underlying issue.
    let old_primary_ok = old
        .primary_key()
        .filter(|k| crate::storage::EncryptionKey::from_hex(k).is_ok())
        .map(str::to_string);
    let old_legacy_ok = old
        .legacy_key()
        .filter(|k| crate::storage::EncryptionKey::from_hex(k).is_ok())
        .map(str::to_string);

    // Primary key + key_id — only relevant on Aes256GcmProxy. The id is
    // kept only with its own key: a new key without an id gets a derived
    // one (keeping the old id would stamp two keys with one id).
    if let E::Aes256GcmProxy {
        key: ref mut new_key,
        key_id: ref mut new_kid,
        ..
    } = new
    {
        merge_kept_field(probe.key, new_key, old_primary_ok.as_deref());
        if let E::Aes256GcmProxy {
            key: old_key,
            key_id: old_kid,
            ..
        } = old
        {
            if new_key.is_some() && new_key == old_key {
                merge_kept_field(probe.key_id, new_kid, old_kid.as_deref());
            }
        }
    }

    // Retirement of the old proxy key (correctness x-ray C3 for mode
    // flips; explore finding 2 for rotations). The admin UI never sees
    // the key (GET redacts it), so the server must keep it: without
    // this every historical object reads as "encrypted with key id X,
    // backend configured with key id Y".
    if let Some(old_primary) = &old_primary_ok {
        let old_kid = effective_proxy_key_id(backend_name, old).unwrap_or_default();
        let retired = match &*new {
            E::Aes256GcmProxy { key: Some(k), .. } => k != old_primary,
            E::Aes256GcmProxy { key: None, .. } => false,
            _ => true,
        };
        if retired {
            if let Some(new_kid) = effective_proxy_key_id(backend_name, new) {
                if new_kid == old_kid {
                    return Err(format!(
                        "backend '{backend_name}': the encryption key changes but the key id \
                         stays '{old_kid}'. Objects written under the old key would be decrypted \
                         with the new key and fail. Remove `key_id` (the id is then derived from \
                         the key) or set a new one."
                    ));
                }
            }
            // A merge-patch keeps the OLD legacy value in `new`; only a
            // different value (or the probe) means the body chose one.
            let body_sets_legacy = probe.legacy_key == Presence::Set
                || (new.legacy_key().is_some() && new.legacy_key() != old.legacy_key());
            if probe.legacy_key != Presence::Null && !body_sets_legacy {
                if old_legacy_ok.as_deref().is_some_and(|l| l != old_primary) {
                    let held_kid = crate::deltaglider::effective_legacy_key_id(backend_name, old)
                        .unwrap_or_default();
                    return Err(format!(
                        "backend '{backend_name}': the current key must become the legacy \
                         (decrypt-only) key, but the legacy slot still holds key id \
                         '{held_kid}', and objects can still need it. Re-encrypt the buckets \
                         on this backend, then remove `legacy_key` / `legacy_key_id` and change \
                         the key again. To drop the old legacy key on purpose, send \
                         `legacy_key` explicitly."
                    ));
                }
                if let Some(slot) = new.legacy_key_mut() {
                    *slot = Some(old_primary.clone());
                }
                set_legacy_key_id(new, Some(old_kid));
                return Ok(());
            }
        }
    }

    // Legacy shim key preservation — same-slot absent-in-body.
    // Explicit operator intent (a legacy_key in the body) always wins.
    // Uses the H8-validated variable so malformed hex doesn't
    // propagate. The id travels with the key: a key restored without
    // its id would get a different derived id and match nothing.
    if let Some(new_legacy) = new.legacy_key_mut() {
        if merge_kept_field(probe.legacy_key, new_legacy, old_legacy_ok.as_deref())
            && new.legacy_key_id().is_none()
        {
            set_legacy_key_id(new, old.legacy_key_id().map(str::to_string));
        }
    }
    Ok(())
}

/// [`preserve_backend_encryption_secrets`] over the singleton and every
/// named backend (matched by name). Shared by the section PUT and the
/// document apply so both write paths keep the same key rules.
pub(crate) fn preserve_all_backend_encryption(
    new_cfg: &mut crate::config::Config,
    old_cfg: &crate::config::Config,
    probe: &BackendEncryptionKeyProbe,
) -> Result<(), String> {
    preserve_backend_encryption_secrets(
        "default",
        &mut new_cfg.backend_encryption,
        &old_cfg.backend_encryption,
        probe.for_singleton(),
    )?;
    for new_named in &mut new_cfg.backends {
        if let Some(old_named) = old_cfg.backends.iter().find(|n| n.name == new_named.name) {
            preserve_backend_encryption_secrets(
                &new_named.name,
                &mut new_named.encryption,
                &old_named.encryption,
                probe.for_named(&new_named.name),
            )?;
        }
    }
    Ok(())
}

/// The id a proxy-AES backend stamps on the objects it writes: the
/// explicit `key_id`, else derived from the backend name and the key
/// (same rule as the engine wrapper). None for other modes or an
/// unparseable key.
fn effective_proxy_key_id(
    backend_name: &str,
    enc: &crate::config::BackendEncryptionConfig,
) -> Option<String> {
    match enc {
        crate::config::BackendEncryptionConfig::Aes256GcmProxy {
            key: Some(hex),
            key_id,
            ..
        } => match key_id {
            Some(explicit) => Some(explicit.clone()),
            None => derive_hex_key_id(backend_name, hex),
        },
        _ => None,
    }
}

fn derive_hex_key_id(name: &str, hex: &str) -> Option<String> {
    let parsed = crate::storage::EncryptionKey::from_hex(hex).ok()?;
    Some(crate::deltaglider::derive_key_id(name, &parsed.0))
}

fn set_legacy_key_id(enc: &mut crate::config::BackendEncryptionConfig, id: Option<String>) {
    use crate::config::BackendEncryptionConfig as E;
    match enc {
        E::None { legacy_key_id, .. }
        | E::Aes256GcmProxy { legacy_key_id, .. }
        | E::SseKms { legacy_key_id, .. }
        | E::SseS3 { legacy_key_id, .. } => *legacy_key_id = id,
    }
}

/// Recursively diff two JSON values. Leaves surface as
/// `{before, after}` pairs keyed by dotted path. Arrays are treated
/// as opaque leaves (either equal or both surfaces); that's sufficient
/// for the UI's "what changed" summary without introducing list-diff
/// complexity here.
fn shallow_diff(
    prefix: &str,
    old: &serde_json::Value,
    new: &serde_json::Value,
    out: &mut serde_json::Map<String, serde_json::Value>,
) {
    match (old, new) {
        (serde_json::Value::Object(o), serde_json::Value::Object(n)) => {
            let mut keys: std::collections::BTreeSet<&String> = o.keys().collect();
            keys.extend(n.keys());
            for k in keys {
                let child_prefix = if prefix.is_empty() {
                    k.clone()
                } else {
                    format!("{}.{}", prefix, k)
                };
                let ov = o.get(k).unwrap_or(&serde_json::Value::Null);
                let nv = n.get(k).unwrap_or(&serde_json::Value::Null);
                shallow_diff(&child_prefix, ov, nv, out);
            }
        }
        _ => {
            if old != new {
                let mut pair = serde_json::Map::new();
                pair.insert("before".to_string(), old.clone());
                pair.insert("after".to_string(), new.clone());
                out.insert(prefix.to_string(), serde_json::Value::Object(pair));
            }
        }
    }
}

#[cfg(test)]
mod tests;

#[cfg(test)]
mod diff_fingerprint_tests;
