//! Section-level admin config API (Wave 1 of the admin UI revamp).
//!
//! Provides section-scoped GET / PUT / validate endpoints:
//!
//! - `GET  /api/admin/config/section/:name[?format=yaml]`
//!   Returns the one named section (`admission` / `access` / `storage` /
//!   `advanced`) of the runtime config, with secrets redacted. JSON by
//!   default; `?format=yaml` emits the canonical YAML for that section only.
//! - `PUT  /api/admin/config/section/:name`
//!   Partial update: accepts JSON for the named section and replaces the
//!   corresponding slice of the in-memory [`Config`]. Routes through the
//!   shared [`super::apply_config_transition`] helper so field-level PATCH,
//!   document-level APPLY, and section-level PUT are all one transition
//!   story.
//! - `POST /api/admin/config/section/:name/validate`
//!   Dry-run variant: parses + validates the section body, computes the
//!   would-be diff, returns `{ok, warnings[], diff}`. No state change.
//!
//! The wire shape for each section is exactly the in-memory type in
//! [`crate::config_sections`] (`AdmissionSection`, `AccessSection`,
//! `StorageSection`, `AdvancedSection`) — so the UI's JSON schema is the
//! same one generated by `schemars` for the YAML view. One schema drives
//! both surfaces.
//!
//! ## Why this layer exists
//!
//! The UI revamp (`docs/plan/admin-ui-revamp.md` §6) needs a scope between
//! the existing *field-level* PATCH (which takes an ad-hoc flat JSON that
//! doesn't match the YAML document) and the *document-level* APPLY (which
//! requires the operator to ship a full canonical YAML even to edit one
//! toggle). The section API gives the UI a natural atomic unit — "apply
//! my Admission section edits, leave Access / Storage / Advanced alone" —
//! while keeping the same hot-reload + persist semantics as the full-
//! document path.

use axum::extract::{Path, Query, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::IntoResponse;
use axum::Json;
use serde::{Deserialize, Serialize};
use std::sync::Arc;

use super::super::{audit_log, AdminState};
use super::{active_config_path, apply_config_transition};
use crate::config_sections::{
    AccessSection, AdmissionSection, AdvancedSection, SectionedConfig, StorageSection,
};

/// Names of the four sections the API understands. Kept as a small enum
/// rather than a string for exhaustiveness — the match in
/// [`replace_section`] must cover every case; adding a fifth section
/// breaks this file noisily until every branch is updated.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SectionName {
    Admission,
    Access,
    Storage,
    Advanced,
}

impl SectionName {
    fn parse(s: &str) -> Option<Self> {
        match s {
            "admission" => Some(Self::Admission),
            "access" => Some(Self::Access),
            "storage" => Some(Self::Storage),
            "advanced" => Some(Self::Advanced),
            _ => None,
        }
    }

    fn as_str(self) -> &'static str {
        match self {
            Self::Admission => "admission",
            Self::Access => "access",
            Self::Storage => "storage",
            Self::Advanced => "advanced",
        }
    }
}

/// Query params for the section GET endpoint.
#[derive(Deserialize, Default)]
pub struct SectionGetQuery {
    /// `"yaml"` to return canonical YAML for this section. Omitted /
    /// anything else returns JSON.
    #[serde(default)]
    format: Option<String>,
}

/// Response body for section PUT + validate.
///
/// Mirrors [`super::ConfigValidateResponse`] in spirit but carries a diff
/// list — the UI renders this inside the plan → diff → apply dialog
/// described in the revamp plan §5.3.
#[derive(Serialize)]
pub struct SectionApplyResponse {
    /// `true` when the section was applied (PUT) or would apply cleanly
    /// (validate). `false` when validation rejected the body; the `error`
    /// field carries the reason.
    pub ok: bool,
    /// Human-readable warnings — same contract as the field-level PATCH:
    /// the HTTP status stays 200 and warnings narrate any partial / best-
    /// effort outcomes (invalid log_level, IAM-mode-gated legacy creds,
    /// etc.). Rendered in the Apply dialog above the confirm button.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub warnings: Vec<String>,
    /// `true` when at least one field in the transition is in the restart-
    /// required set (see [`apply_config_transition`]). The UI surfaces this
    /// as a banner in the Apply dialog so operators don't ship a
    /// restart-requiring change during a busy window without noticing.
    #[serde(default)]
    pub requires_restart: bool,
    /// Only set on PUT success — path the persisted YAML was written to.
    /// Absent for dry-run (validate) responses.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persisted_path: Option<String>,
    /// Machine-readable error string when `ok: false`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// JSON Merge Patch showing what would change relative to the current
    /// runtime config, scoped to the submitted section. The UI renders it
    /// in the Apply dialog as a side-by-side diff (§5.3 of the plan).
    ///
    /// The structure is `{ section_name: { field_path: {before, after} } }`
    /// — a shallow per-field diff, not a full structural diff. That's
    /// enough for the UI's "cache_size_mb: 256 → 2048" view; deeper diffs
    /// (e.g. which bucket entry changed) are shown by the richer section
    /// editors directly, not by this endpoint.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub diff: Option<serde_json::Value>,
}

/// `GET /api/admin/config/section/:name` — serialize the named slice of
/// the runtime config.
///
/// JSON by default (matches the shape the UI's form controllers expect).
/// `?format=yaml` emits the canonical YAML for that one section — useful
/// for the per-section Copy-as-YAML button described in §3.3 of the plan.
/// Secrets are redacted via the same [`Config::redact_all_secrets`] used
/// by the document-level export.
pub async fn get_section(
    State(state): State<Arc<AdminState>>,
    Path(name): Path<String>,
    Query(query): Query<SectionGetQuery>,
) -> impl IntoResponse {
    let Some(section) = SectionName::parse(&name) else {
        return (
            StatusCode::NOT_FOUND,
            Json(SectionApplyResponse {
                ok: false,
                warnings: vec![],
                requires_restart: false,
                persisted_path: None,
                error: Some(format!(
                    "unknown section '{}'; valid names: admission, access, storage, advanced",
                    name
                )),
                diff: None,
            }),
        )
            .into_response();
    };

    let cfg = state.config.read().await;
    let redacted = cfg.redact_all_secrets();
    let sectioned = SectionedConfig::from_flat(&redacted);
    drop(cfg);

    let yaml_format = query.format.as_deref() == Some("yaml");

    match section {
        SectionName::Admission => emit_section(
            section,
            sectioned.admission.unwrap_or_default(),
            yaml_format,
        ),
        SectionName::Access => emit_section(section, sectioned.access, yaml_format),
        SectionName::Storage => emit_section(section, sectioned.storage, yaml_format),
        SectionName::Advanced => emit_section(section, sectioned.advanced, yaml_format),
    }
}

/// Serialize one section in the requested format. Factored out so
/// [`get_section`] stays one match arm per section — the generic makes
/// the format branch uniform.
fn emit_section<T: serde::Serialize>(
    section: SectionName,
    value: T,
    yaml_format: bool,
) -> axum::response::Response {
    if yaml_format {
        // Emit `<name>:\n  ...fields...` — matches the shape this same
        // block would take inside the full canonical YAML. The empty-
        // section case (e.g. `admission:` with no blocks) is normal
        // and not an error; the client renders an editor seeded with
        // the section's defaults.
        let mut map = serde_yaml::Mapping::new();
        let value_yaml = match serde_yaml::to_value(&value) {
            Ok(v) => v,
            Err(e) => {
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    format!("failed to serialize section to YAML: {}", e),
                )
                    .into_response();
            }
        };
        map.insert(
            serde_yaml::Value::String(section.as_str().to_string()),
            value_yaml,
        );
        let doc = serde_yaml::Value::Mapping(map);
        match serde_yaml::to_string(&doc) {
            Ok(s) => (
                StatusCode::OK,
                [(axum::http::header::CONTENT_TYPE, "application/yaml")],
                s,
            )
                .into_response(),
            Err(e) => (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("failed to serialize section to YAML: {}", e),
            )
                .into_response(),
        }
    } else {
        (StatusCode::OK, Json(value)).into_response()
    }
}

/// `PUT /api/admin/config/section/:name` — apply a section partial.
///
/// Body is JSON matching the target section's shape (the same type used
/// by the YAML serializer — no ad-hoc wrapper). The section replaces its
/// slice in the in-memory `SectionedConfig`; the rest of the document
/// stays intact. Transition happens under a single write lock:
///
/// 1. Clone the current `Config` into a prospective `new_cfg`.
/// 2. Deserialize the body into the target section struct.
/// 3. Replace the one field on a `SectionedConfig::from_flat(&new_cfg)`.
/// 4. `into_flat()` to collapse back (runs the same `normalize` + admission
///    validation as the YAML path).
/// 5. Preserve runtime secrets across the section (exporting redacts, so
///    a round-trip put would otherwise clear creds).
/// 6. Hand off to [`apply_config_transition`] for hot-reload side effects.
/// 7. Persist atomically.
///
/// The result's `diff` field shows exactly what changed relative to the
/// pre-PUT state so the Apply dialog can display it.
pub async fn put_section(
    State(state): State<Arc<AdminState>>,
    Path(name): Path<String>,
    headers: HeaderMap,
    body: Json<serde_json::Value>,
) -> impl IntoResponse {
    apply_section(
        state,
        name,
        body.0,
        ApplyMode::PersistAndApply,
        Some(headers),
    )
    .await
}

/// `POST /api/admin/config/section/:name/validate` — dry-run a section apply.
///
/// Same inputs as PUT, but no state change and no persist. Returns
/// `ok`, the computed diff, and warnings. The UI calls this when the
/// operator presses Apply: the diff is rendered in the confirmation
/// modal (§5.3), and a second click on "Apply and Persist" fires the
/// real PUT. Keeping validate in the same module as PUT makes the
/// "validate-then-apply" contract structurally obvious.
pub async fn validate_section(
    State(state): State<Arc<AdminState>>,
    Path(name): Path<String>,
    body: Json<serde_json::Value>,
) -> impl IntoResponse {
    apply_section(state, name, body.0, ApplyMode::DryRun, None).await
}

/// Whether a section operation should mutate + persist, or only report
/// the would-be result.
enum ApplyMode {
    DryRun,
    PersistAndApply,
}

/// Shared implementation of PUT + validate. The only difference is
/// whether to mutate state and persist at the end — every parse,
/// validate, diff, and transition step runs identically so the two
/// surfaces can't drift.
async fn apply_section(
    state: Arc<AdminState>,
    name: String,
    body: serde_json::Value,
    mode: ApplyMode,
    headers: Option<HeaderMap>,
) -> axum::response::Response {
    let Some(section) = SectionName::parse(&name) else {
        return (
            StatusCode::NOT_FOUND,
            Json(SectionApplyResponse {
                ok: false,
                warnings: vec![],
                requires_restart: false,
                persisted_path: None,
                error: Some(format!(
                    "unknown section '{}'; valid names: admission, access, storage, advanced",
                    name
                )),
                diff: None,
            }),
        )
            .into_response();
    };

    // Take the write lock once for the whole transition — the same
    // lock-scope discipline as `apply_config_doc`, so a racing PATCH
    // can't sneak between our compare and swap.
    let mut cfg = state.config.write().await;
    let old_cfg = cfg.clone();

    // Project current config → sectioned shape → replace one slice →
    // collapse back. The replacement does NOT touch secrets on the
    // current config (we merge them back after); the operator's body
    // is treated as "the new non-secret state of this section".
    let mut sectioned = SectionedConfig::from_flat(&old_cfg);
    if let Err(err) = replace_section(&mut sectioned, section, &body) {
        return (
            StatusCode::BAD_REQUEST,
            Json(SectionApplyResponse {
                ok: false,
                warnings: vec![],
                requires_restart: false,
                persisted_path: None,
                error: Some(err),
                diff: None,
            }),
        )
            .into_response();
    }

    // Collapse back to flat. This runs the same `storage.normalize()`
    // and `AdmissionSpec::validate()` the YAML loader runs — structural
    // errors in the body surface here with the same messages the YAML
    // view would show.
    let mut new_cfg = match sectioned.into_flat() {
        Ok(c) => c,
        Err(err) => {
            return (
                StatusCode::BAD_REQUEST,
                Json(SectionApplyResponse {
                    ok: false,
                    warnings: vec![],
                    requires_restart: false,
                    persisted_path: None,
                    error: Some(err),
                    diff: None,
                }),
            )
                .into_response();
        }
    };

    // Preserve runtime secrets across the section edit. The GET
    // surfaces (export, section GET) redact every secret; a naïve
    // round-trip (GET → edit → PUT) would therefore post None for
    // every creds pair. We mirror the document-level apply's
    // "preserve when None on the incoming side" semantics so section
    // round-trips don't silently clear authentication state.
    //
    // Infra secrets (bootstrap hash, encryption key) are always
    // preserved — a PUT to any section that touches the `advanced`
    // slice would otherwise zero them.
    new_cfg.bootstrap_password_hash = old_cfg.bootstrap_password_hash.clone();
    new_cfg.encryption_key = old_cfg.encryption_key.clone();
    // Top-level SigV4 creds (the legacy bootstrap key pair living on
    // `Config` directly) are preserved when the incoming value is
    // None. Explicit rotation — setting a new value — still works;
    // only the null-on-both-halves case triggers preservation. This
    // is the same both-or-neither contract `preserve_sigv4_pair`
    // implements on the document-level path.
    if new_cfg.access_key_id.is_none() && new_cfg.secret_access_key.is_none() {
        new_cfg.access_key_id = old_cfg.access_key_id.clone();
        new_cfg.secret_access_key = old_cfg.secret_access_key.clone();
    }
    // Backend creds: identical logic for each backend. The sectioned
    // `storage` replacement drops these via redaction; restore from
    // old when missing.
    preserve_backend_secrets(&mut new_cfg.backend, &old_cfg.backend);
    for new_named in &mut new_cfg.backends {
        if let Some(old_named) = old_cfg.backends.iter().find(|n| n.name == new_named.name) {
            preserve_backend_secrets(&mut new_named.backend, &old_named.backend);
        }
    }

    // Validate semantically via `Config::check` (runs the same
    // warnings pipeline the document-level apply runs).
    let warnings_from_check = new_cfg.check();

    // Compute the diff before we potentially swap. This is the shape
    // the UI renders in the Apply dialog.
    let diff = compute_section_diff(section, &old_cfg, &new_cfg);

    // Compute `requires_restart` from the old vs. new config directly
    // (no state mutation). The same fields
    // [`apply_config_transition`] checks — `listen_addr`,
    // `cache_size_mb` — are compared here without touching the
    // runtime. Dry-run stays stateless.
    let requires_restart = restart_required_between(&old_cfg, &new_cfg);

    // Dry-run: no state mutation, no engine rebuild. The apply dialog
    // gets the diff + warnings_from_check + restart-required flag so
    // the operator can review before confirming. Engine-rebuild
    // failures (e.g. bad S3 endpoint) are only surfaced on the real
    // PUT — the risk of making dry-run briefly flip the runtime to
    // the proposed state (which admission_chain / engine / iam_state
    // are all ArcSwap-observed, i.e. concurrent request-serving code
    // can see the flip) is not worth catching engine errors earlier
    // than they happen in PUT anyway.
    if matches!(mode, ApplyMode::DryRun) {
        return (
            StatusCode::OK,
            Json(SectionApplyResponse {
                ok: true,
                warnings: warnings_from_check,
                requires_restart,
                persisted_path: None,
                error: None,
                diff: Some(diff),
            }),
        )
            .into_response();
    }

    // PersistAndApply: run the full transition (engine rebuild + log
    // reload + IAM swap + snapshot rebuilds). On failure we return
    // UNPROCESSABLE_ENTITY — caller fixes and re-applies.
    let (transition_warnings, transition_restart) =
        match apply_config_transition(&state, &old_cfg, &new_cfg).await {
            Ok(pair) => pair,
            Err(e) => {
                return (
                    StatusCode::UNPROCESSABLE_ENTITY,
                    Json(SectionApplyResponse {
                        ok: false,
                        warnings: warnings_from_check,
                        requires_restart: false,
                        persisted_path: None,
                        error: Some(format!(
                            "Failed to apply section '{}' (no state changed): {}",
                            section.as_str(),
                            e
                        )),
                        diff: Some(diff),
                    }),
                )
                    .into_response();
            }
        };

    // Transition's `requires_restart` is authoritative for the PUT
    // response (it's the same value the field-level PATCH and
    // document-level APPLY return). Our earlier `requires_restart`
    // from `restart_required_between` was only for the dry-run path;
    // it should match what the transition just returned but we always
    // defer to the transition's computation here.
    debug_assert_eq!(
        requires_restart, transition_restart,
        "dry-run's restart_required_between must agree with apply_config_transition"
    );
    let requires_restart = transition_restart;

    // Swap the config in memory and persist.
    *cfg = new_cfg;

    let persist_path = active_config_path(&state);
    let (persisted, persisted_path, status, persist_warning) = match cfg.persist_to_file(&persist_path) {
        Ok(()) => (true, Some(persist_path.clone()), StatusCode::OK, None),
        Err(e) => (
            false,
            None,
            StatusCode::INTERNAL_SERVER_ERROR,
            Some(format!(
                "Applied section '{}' in memory but FAILED to persist to {}: {}. Server will revert on next restart — fix the IO and re-apply.",
                section.as_str(),
                persist_path,
                e
            )),
        ),
    };

    let _ = persisted; // feedback to client via warnings + status

    if let Some(h) = headers {
        audit_log(
            &format!("apply_config_section:{}", section.as_str()),
            "admin",
            &persist_path,
            &h,
        );
    }

    let warnings: Vec<String> = warnings_from_check
        .into_iter()
        .chain(transition_warnings)
        .chain(persist_warning)
        .collect();

    (
        status,
        Json(SectionApplyResponse {
            ok: true,
            warnings,
            requires_restart,
            persisted_path,
            error: None,
            diff: Some(diff),
        }),
    )
        .into_response()
}

/// Replace one named section on a `SectionedConfig` from a JSON body.
///
/// The body's schema must match the target section's type — anything
/// else is rejected with a serde error. The match is exhaustive on
/// [`SectionName`] so adding a section forces a local update here.
fn replace_section(
    sectioned: &mut SectionedConfig,
    section: SectionName,
    body: &serde_json::Value,
) -> Result<(), String> {
    match section {
        SectionName::Admission => {
            let parsed: AdmissionSection = serde_json::from_value(body.clone())
                .map_err(|e| format!("invalid admission section body: {}", e))?;
            sectioned.admission = if parsed.blocks.is_empty() {
                None
            } else {
                Some(parsed)
            };
        }
        SectionName::Access => {
            let parsed: AccessSection = serde_json::from_value(body.clone())
                .map_err(|e| format!("invalid access section body: {}", e))?;
            sectioned.access = parsed;
        }
        SectionName::Storage => {
            let parsed: StorageSection = serde_json::from_value(body.clone())
                .map_err(|e| format!("invalid storage section body: {}", e))?;
            sectioned.storage = parsed;
        }
        SectionName::Advanced => {
            let parsed: AdvancedSection = serde_json::from_value(body.clone())
                .map_err(|e| format!("invalid advanced section body: {}", e))?;
            sectioned.advanced = parsed;
        }
    }
    Ok(())
}

/// Compute the per-field diff for one section.
///
/// Semantics: project both configs into a `SectionedConfig`, pick the
/// named section off each, run a shallow recursive diff on the two
/// JSON representations, and return
/// `{ "<section>": { "<path>": {"before": ..., "after": ...} } }`.
///
/// The diff intentionally collapses equal values — the UI only wants to
/// render what changed. For Admission, the blocks list is diffed by
/// name so reorders surface as a single pair of before/after lists
/// rather than N spurious per-index changes. (Other sections are
/// scalar-heavy so per-field is enough.)
fn compute_section_diff(
    section: SectionName,
    old_cfg: &crate::config::Config,
    new_cfg: &crate::config::Config,
) -> serde_json::Value {
    let old_sectioned = SectionedConfig::from_flat(&old_cfg.redact_all_secrets());
    let new_sectioned = SectionedConfig::from_flat(&new_cfg.redact_all_secrets());

    let (old_json, new_json) = match section {
        SectionName::Admission => (
            serde_json::to_value(old_sectioned.admission.unwrap_or_default()).unwrap_or_default(),
            serde_json::to_value(new_sectioned.admission.unwrap_or_default()).unwrap_or_default(),
        ),
        SectionName::Access => (
            serde_json::to_value(old_sectioned.access).unwrap_or_default(),
            serde_json::to_value(new_sectioned.access).unwrap_or_default(),
        ),
        SectionName::Storage => (
            serde_json::to_value(old_sectioned.storage).unwrap_or_default(),
            serde_json::to_value(new_sectioned.storage).unwrap_or_default(),
        ),
        SectionName::Advanced => (
            serde_json::to_value(old_sectioned.advanced).unwrap_or_default(),
            serde_json::to_value(new_sectioned.advanced).unwrap_or_default(),
        ),
    };

    let mut diff = serde_json::Map::new();
    shallow_diff("", &old_json, &new_json, &mut diff);

    let mut out = serde_json::Map::new();
    out.insert(
        section.as_str().to_string(),
        serde_json::Value::Object(diff),
    );
    serde_json::Value::Object(out)
}

/// Preserve backend creds across a section round-trip.
///
/// Both `new` and `old` are S3 backends? Only when the incoming pair
/// is both-None do we preserve the current creds — matches the
/// "both-or-neither" contract on the top-level SigV4 pair. Asymmetric
/// pairs (only `access_key_id` set, only `secret_access_key` set) are
/// left as-is so the resulting config surfaces the user's exact
/// intent — eventual auth failure is louder than silently cross-
/// wiring.
///
/// Any other type pair (S3 ↔ filesystem, filesystem ↔ filesystem) is
/// a no-op — filesystem backends carry no creds.
fn preserve_backend_secrets(
    new: &mut crate::config::BackendConfig,
    old: &crate::config::BackendConfig,
) {
    if let (
        crate::config::BackendConfig::S3 {
            access_key_id: new_akid,
            secret_access_key: new_sk,
            ..
        },
        crate::config::BackendConfig::S3 {
            access_key_id: old_akid,
            secret_access_key: old_sk,
            ..
        },
    ) = (new, old)
    {
        if new_akid.is_none() && new_sk.is_none() {
            *new_akid = old_akid.clone();
            *new_sk = old_sk.clone();
        }
    }
}

/// Non-mutating predicate: would applying `new` on top of `old` require
/// a server restart to take effect?
///
/// Mirrors the restart-required set inside [`apply_config_transition`]:
/// `listen_addr` (HTTP socket re-bind) and `cache_size_mb` (moka cache
/// max capacity is set once at engine construction). Keeping this
/// function separate is what lets the dry-run `/validate` path skip
/// the transition entirely — running [`apply_config_transition`] in
/// dry-run would mutate `ArcSwap`-backed state (admission_chain,
/// engine, iam_state) that request-serving code reads lock-free,
/// briefly flipping the runtime to the proposed config before we roll
/// back.
///
/// Sync with [`apply_config_transition`] when the restart-required
/// list grows.
fn restart_required_between(old: &crate::config::Config, new: &crate::config::Config) -> bool {
    old.listen_addr != new.listen_addr || old.cache_size_mb != new.cache_size_mb
}

/// Recursively diff two JSON values. Leaves surface as
/// `{before, after}` pairs keyed by dotted path. Arrays are treated
/// as opaque leaves (either equal or both surfaces); that's sufficient
/// for the UI's "what changed" summary without introducing list-diff
/// complexity here.
fn shallow_diff(
    prefix: &str,
    old: &serde_json::Value,
    new: &serde_json::Value,
    out: &mut serde_json::Map<String, serde_json::Value>,
) {
    match (old, new) {
        (serde_json::Value::Object(o), serde_json::Value::Object(n)) => {
            let mut keys: std::collections::BTreeSet<&String> = o.keys().collect();
            keys.extend(n.keys());
            for k in keys {
                let child_prefix = if prefix.is_empty() {
                    k.clone()
                } else {
                    format!("{}.{}", prefix, k)
                };
                let ov = o.get(k).unwrap_or(&serde_json::Value::Null);
                let nv = n.get(k).unwrap_or(&serde_json::Value::Null);
                shallow_diff(&child_prefix, ov, nv, out);
            }
        }
        _ => {
            if old != new {
                let mut pair = serde_json::Map::new();
                pair.insert("before".to_string(), old.clone());
                pair.insert("after".to_string(), new.clone());
                out.insert(prefix.to_string(), serde_json::Value::Object(pair));
            }
        }
    }
}
